/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MySignature {
    }
}
declare global {
    interface HTMLMySignatureElement extends Components.MySignature, HTMLStencilElement {
    }
    var HTMLMySignatureElement: {
        prototype: HTMLMySignatureElement;
        new (): HTMLMySignatureElement;
    };
    interface HTMLElementTagNameMap {
        "my-signature": HTMLMySignatureElement;
    }
}
declare namespace LocalJSX {
    interface MySignature {
    }
    interface IntrinsicElements {
        "my-signature": MySignature;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-signature": LocalJSX.MySignature & JSXBase.HTMLAttributes<HTMLMySignatureElement>;
        }
    }
}
